"""empty message

Revision ID: b0248c9038a5
Revises: 
Create Date: 2023-08-16 14:19:35.857503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0248c9038a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('hoa', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('template',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('template_issue_number', sa.Integer(), nullable=False),
    sa.Column('template_volume_number', sa.Integer(), nullable=False),
    sa.Column('template_date', sa.DateTime(), nullable=False),
    sa.Column('template_hoa', sa.String(length=200), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')
    op.drop_table('user')
    # ### end Alembic commands ###
